server:
  port: 8080


spring:
  application:
    name: mimo

  profiles:
    include: env
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
 
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    defer-datasource-initialization: true

jwt:
  access:
    token:
      expiration:
        seconds: 5184000
#  refresh:
#    token:
#      expiration:
#        seconds: 604800
  token:
    secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    root: info
    com.ssafy.mimo: DEBUG

